volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:v0.20.7
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./flows:/app/flows
      - ./gcp_key.json:/creds/gcp_key.json:ro
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          default:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@kestra.io"
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
      GOOGLE_APPLICATION_CREDENTIALS: /creds/key.json
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started

  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.8.0
    working_dir: /project
    entrypoint: "dbt"
    volumes:
      - ./dbt/taxi_rides_ny:/project
      - ./gcp_key.json:/creds/key.json:ro
    environment:
      DBT_PROFILES_DIR: /project
      GOOGLE_APPLICATION_CREDENTIALS: /creds/key.json
